controller_manager_ns: moveit_simple_controller_manager
controller_list:
 - name: /arm_control/arm_traj_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - arm_joint_0
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
 - name: /sensor_head_control/sensor_head_traj_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - sensor_head_yaw_joint
      - sensor_head_pitch_joint
 - name: /gripper_control/gripper_roll_traj_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - arm_joint_4
 - name: /gripper_control/gripper_grasp_traj_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - gripper_joint_0
 - name: /flipper_control/flipper_traj_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - flipper_joint_1      